# Generated by Django 4.2 on 2023-05-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drone_name_alter_dronecategory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='has_it_competed',
            new_name='has_it_completed',
        ),
    ]
