# Generated by Django 4.2 on 2023-05-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_rename_has_it_competed_drone_has_it_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='has_it_completed',
            new_name='has_it_competed',
        ),
    ]
